### ISSUE TITLE
Goals for the benchmarking tool

### ISSUE THREAD

**Issue by moorts** [lkno0705/MatrixMultiplication#19]
What exactly are the functions the benchmarking tool should fulfill? Should it be system independant, or is it fine if it only runs on @lkno0705's system? (Since absolute paths are used in the current version).
Also @lkno0705 what is the goal for the markdown-creation script? Do you plan on extending it so it creates the whole README and calculates the execution times?

**Comment by lkno0705** [comment]
The benchmarkingtool is primarly intended to run on my machine because we areusing it for the benchmarks. I indeed plan to extend the markdown-creation script, so it creates and sorts the complete README.md files. If needed, we could also change the implementation, so it runs on every machine. But some execs are optimized to run on Ryzen / Zen 2 Architecture.
